// Package media holds the media-library entity, the supported MIME types with
// their validation limits, and the MediaStore abstraction that keeps byte
// storage replaceable (local disk now, object storage later).
package media

import (
	"context"
	"io"
	"time"
)

// MaxUploadBytes is the hard cap for one uploaded media file (5 MiB).
const MaxUploadBytes = 5 * 1024 * 1024

// Supported media MIME types.
const (
	MIMEPNG  = "image/png"
	MIMEJPEG = "image/jpeg"
	MIMEGIF  = "image/gif"
	MIMEWEBP = "image/webp"
	MIMESVG  = "image/svg+xml"
)

// Asset is a stored media object as recorded in primary storage.
type Asset struct {
	ID           int64
	URL          string
	OriginalName string
	MIME         string
	SizeBytes    int64
	Width        int
	Height       int
	CreatedBy    int64
	CreatedAt    time.Time
}

// StoredFile is a readable media object.
type StoredFile interface {
	io.ReadSeekCloser
	ModTime() time.Time
	Size() int64
}

// Store persists and serves media bytes. filename is always a single path
// segment generated by the service (never client input).
type Store interface {
	Put(ctx context.Context, filename string, content io.Reader) error
	Open(filename string) (StoredFile, error)
	Delete(filename string) error
}
